version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintech
    ports:
      - '5432:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
  api:
    build: ../../apps/api
    env_file:
      - ../../apps/api/.env.example
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - minio
  web:
    build: ../../apps/web
    env_file:
      - ../../apps/web/.env.example
    ports:
      - '3001:3000'
    depends_on:
      - api
